### Variables
@baseUrl = http://localhost:4000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1M2JlNWU3MC04NGNkLTRjZTUtYWViNS01MzkzZmFlMDFkYjciLCJlbWFpbCI6InlvdUBleGFtcGxlLmNvbSIsImlhdCI6MTc3NjgwMjI3OSwiZXhwIjoxNzc5Mzk0Mjc5fQ.WIThvdV_KSyYqHcL3I295b8Z0n547328nIDwmR7RdQQ

### 1. Inscription (Sign-up)
POST {{baseUrl}}/sign-up
Content-Type: application/json

{
    "email": "​you@example.com,
    "password": "password123"
}

### 2. Connexion (Login)
# Note: Teste le authLimiter en cliquant 6 fois rapidement !
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "you@example.com",
    "password": "12345678"
}

### 3. Update Profil (Protégé)
POST {{baseUrl}}/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "email": "email@email.com",
    "password": "password123",
    "newPassword": "newPassword456"
}

### 4. Renouveler le Token (Rotate)
POST {{baseUrl}}/rotate-token
Authorization: Bearer {{token}}

### 5. Supprimer le compte (Delete)
POST {{baseUrl}}/delete
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "email": "email@email.com",
    "password": "newPassword456"
}