# Generated by Django 6.0.3 on 2026-03-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='verified_at',
        ),
    ]
