# Generated by Django 6.0.3 on 2026-03-08 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_users_is_staff_alter_users_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvitationCode',
        ),
    ]
